#!/usr/bin/env python3
"""Build descriptive tables from completed, audited path-control summaries.

No evaluation, checkpoint selection, training, or hypothesis testing occurs here.
Both budgets and all seeds remain in the Markdown report. The paper tables use
the 160-epoch selected checkpoints and show the preserved 120-epoch slice too.
"""
from pathlib import Path
import csv
import hashlib
import json

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
PAPER = ROOT / "paper/spin_direct_path_controls_cn_20260917"
VARIANTS = ("spin_direct", "context_only", "direct_only")
LABELS = {"spin_direct": "SPIN+Direct", "context_only": "Context-only",
          "direct_only": "Direct-only", "linear_cpu": "Linear (CPU)"}
DATASETS = {"abilene": "Abilene", "geant": "GEANT"}


def read(path):
    raw = path.read_bytes()
    return json.loads(raw), hashlib.sha256(raw).hexdigest()


def cell(summary, variant, budget, metric):
    item = summary["budgets"][str(budget)]["seed_summaries"][variant]
    assert item["n"] == 2 and item["all_expected_seeds_complete"]
    return item["mean"][metric], item["sample_sd"][metric]


def main():
    sources, summaries, benchmarks = {}, {}, {}
    for dataset in DATASETS:
        directory = "summary" if dataset == "geant" else "summary_abilene"
        path = HERE / directory / "SUMMARY.json"
        summary, sources[str(path.relative_to(ROOT))] = read(path)
        assert summary["dataset"] == dataset
        assert summary["all_six_jobs_complete"] and not summary["independent_test"]
        assert summary["role"] == "development_only"
        for variant in VARIANTS:
            for seed in (41001, 41002):
                job = summary["jobs"][variant][str(seed)]
                assert not job["errors"] and not job["warnings"]
        suffix = "" if dataset == "geant" else "_ABILENE"
        path = HERE / ("INFERENCE_BENCHMARK" + suffix + ".json")
        benchmark, sources[str(path.relative_to(ROOT))] = read(path)
        assert benchmark["state"] == "complete"
        assert set(benchmark["datasets"]) == {dataset}
        summaries[dataset] = summary
        benchmarks[dataset] = benchmark

    md = ["# 完成结果表（自动由已核查记录生成）", "",
          "开发评价；两个配对初始化，三个条件等权。± 为两个种子的样本标准差，不是置信区间。",
          "120 与 160 是同一轨迹的预算截面，不是独立训练重复。NMAE 为主指标，NRMSE 为辅助指标。", "",
          "## 两个预算的主结果", "",
          "| 数据 | 预算 | 模型 | NMAE，均值 ± SD | NRMSE，均值 ± SD |",
          "|---|---:|---|---:|---:|"]
    latex = [r"% Generated by analysis/spin_path_controls_20260917/build_tables.py",
             r"\begin{table*}[t]", r"\centering\small",
             r"\caption{路径对照的开发结果。三个条件等权、两个种子均值$\pm$样本标准差；主指标NMAE越低越好。120/160沿用同一轨迹，Full仅保留历史120轮结果。}",
             r"\label{tab:paths}", r"\begin{tabular}{llrrrr}", r"\toprule",
             r"数据 & 模型 & NMAE (120) & NMAE (160) & NRMSE (120) & NRMSE (160) \\",
             r"\midrule"]
    for dataset, name in DATASETS.items():
        summary = summaries[dataset]
        for budget in (120, 160):
            for variant in VARIANTS:
                ma, sa = cell(summary, variant, budget, "mean_nmae")
                mr, sr = cell(summary, variant, budget, "mean_nrmse")
                md.append(f"| {name} | {budget} | {LABELS[variant]} | {ma:.6f} ± {sa:.6f} | {mr:.6f} ± {sr:.6f} |")
        for variant in VARIANTS:
            cols = [name, LABELS[variant]]
            for metric, budget in (("mean_nmae", 120), ("mean_nmae", 160),
                                   ("mean_nrmse", 120), ("mean_nrmse", 160)):
                mean, sd = cell(summary, variant, budget, metric)
                cols.append(f"${mean:.6f}\\pm{sd:.6f}$")
            latex.append(" & ".join(cols) + r" \\")
        historical = summary["historical_references"]["Full_fixed120"]["summary"]
        cols = [name, "Full (历史)"]
        for metric, budget in (("mean_nmae", 120), ("mean_nmae", 160),
                               ("mean_nrmse", 120), ("mean_nrmse", 160)):
            if budget == 160:
                cols.append("---")
            else:
                cols.append(f"${historical['mean'][metric]:.6f}\\pm{historical['sample_sd'][metric]:.6f}$")
        latex.append(" & ".join(cols) + r" \\")
        md.append(f"| {name} | 120历史 | Full | {historical['mean']['mean_nmae']:.6f} ± {historical['sample_sd']['mean_nmae']:.6f} | {historical['mean']['mean_nrmse']:.6f} ± {historical['sample_sd']['mean_nrmse']:.6f} |")
        if dataset == "abilene":
            latex.append(r"\midrule")
    latex += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]

    md += ["", "## 全部种子与末段诊断", "",
           "末20轮统计只解释轨迹，不改变检查点选择规则；轮次相关，不能当作20次独立重复。", "",
           "| 数据 | 预算 | 模型 | seed | 最佳轮 | 最佳 NMAE | 同点 NRMSE | 末20轮 NMAE中位数 | 末20轮范围 |",
           "|---|---:|---|---:|---:|---:|---:|---:|---:|"]
    for dataset, name in DATASETS.items():
        for budget in (120, 160):
            for variant in VARIANTS:
                for seed in (41001, 41002):
                    item = summaries[dataset]["jobs"][variant][str(seed)]["slices"][str(budget)]
                    tr, met = item["trajectory"], item["metrics"]
                    tail = tr["tail_nmae"]
                    md.append(f"| {name} | {budget} | {LABELS[variant]} | {seed} | {tr['best_epoch']} | {met['mean_nmae']:.6f} | {met['mean_nrmse']:.6f} | {tail['median']:.6f} | {tail['min']:.6f}–{tail['max']:.6f} |")

    md += ["", "## 匹配推理成本", "",
           "H20 上的神经模型与 CPU Linear 分开理解；B8 为每窗摊销耗时，非单请求延迟。",
           "每条件/批量预热5次、计时15次，先取中位数再对三个条件等权。使用拟合窗口测时，不产生新的精度评价。",
           "神经计时包含输入/输出传输、有限性检查和观测复制/裁剪；不含加载权重、统计量、建图及掩码生成。",
           "峰值为PyTorch allocated memory（含常驻模型），不是整卡占用。", "",
           "| 数据 | 模型 | 参数 | B1 ms | B8 ms/窗 | B8峰值 MiB |",
           "|---|---|---:|---:|---:|---:|"]
    latex += [r"\begin{table}[t]", r"\centering\small",
              r"\caption{同一H20的完整推理成本与CPU Linear参考。B8为每窗摊销耗时；显存为PyTorch峰值allocated memory。计时边界见正文。}",
              r"\label{tab:cost}", r"\begin{tabular}{llrrr}",
              r"\toprule", r"数据 & 模型 & B1/ms & B8/ms & MiB \\", r"\midrule"]
    for dataset, name in DATASETS.items():
        for row in benchmarks[dataset]["summary"]:
            method = row["method"]
            b1 = row["b1_mean_condition_median_ms_per_batch"]
            b8 = row["b8_mean_condition_median_ms_per_window"]
            memory = row["b8_max_allocated_mib_including_resident_model"]
            mem = "—" if memory is None else f"{memory:.1f}"
            md.append(f"| {name} | {LABELS[method]} | {row['parameters']} | {b1:.3f} | {b8:.3f} | {mem} |")
            latex.append(f"{name} & {LABELS[method]} & {b1:.2f} & {b8:.2f} & {mem} " + r"\\")
        if dataset == "abilene":
            latex.append(r"\midrule")
    latex += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    md += ["", "## 预定义掩码支持分组（160轮截面）", "",
           "各列为两个种子各自组内NMAE的平均。分组只作解释，不替换全缺失项主指标。",
           "internal：缺失位置前后都有本流观测；boundary：只有单侧本流观测。",
           "sparse/dense：每流4/16个观测。shared_gap：受影响的一半流中的共同10槽缺口；其他流在该区间仍可有观测。",
           "这些是不同分组轴，不能把所有分组的计数直接相加。", "",
           "| 数据 | 条件 | 分组 | SPIN+Direct | Context-only | Direct-only |",
           "|---|---|---|---:|---:|---:|"]
    group_rows = []
    for dataset, name in DATASETS.items():
        jobs = summaries[dataset]["jobs"]
        for condition in ("uniform", "unequal", "unequal_gap"):
            groups = jobs["spin_direct"]["41001"]["slices"]["160"]["groups"][condition]
            for group in groups:
                means = []
                for variant in VARIANTS:
                    values = []
                    for seed in (41001, 41002):
                        record = jobs[variant][str(seed)]["slices"]["160"]["groups"][condition][group]
                        values.append(record["nmae"])
                        group_rows.append(dict(dataset=dataset, variant=variant, seed=seed,
                                               condition=condition, group=group, **record))
                    means.append(sum(values) / 2)
                md.append(f"| {name} | {condition} | {group} | " + " | ".join(f"{value:.6f}" for value in means) + " |")
    with (HERE / "GROUPS160.csv").open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(group_rows[0]))
        writer.writeheader()
        writer.writerows(group_rows)
    md += ["", "## 数值来源", "", "逐条件、掩码支持分组、配对差值和历史参考详见各WAN的SUMMARY.json及CONDITIONS.csv。", ""]
    for path, digest in sources.items():
        md.append(f"- `{path}`：`{digest}`")
    (HERE / "DATA_TABLES_CN.md").write_text("\n".join(md) + "\n")
    PAPER.mkdir(exist_ok=True)
    (PAPER / "results_tables.tex").write_text("\n".join(latex))
    provenance = {"role": "development_only", "independent_test": False,
                  "source_sha256": sources, "script_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}
    (PAPER / "TABLE_PROVENANCE.json").write_text(json.dumps(provenance, indent=2) + "\n")
    print(HERE / "DATA_TABLES_CN.md")
    print(PAPER / "results_tables.tex")


if __name__ == "__main__":
    main()
